[package]
name = "rust_todo"
version = "0.1.0"
edition = "2024"

[dependencies]
http = "1.4.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.148"
uuid = { version = "1.19.0", features = ["v4"] }
